apiVersion: v1
kind: Pod
metadata:
  name: volume-hostpath-demo1
  labels:
    name: volume-hostpath-demo1
spec:
  volumes:
    - name: shared-volume
      hostPath:
        # remember that if you use Minikube, the host here is the Minikube. So, you need to enter the Minikube first
        path: /mnt/nfs_share # please enable nfs first
  containers:
  - name: volume-hostpath-busybox
    image: busybox:1.34
    command: ["tail"]
    args: ["-F", "anything"]
    volumeMounts:
      - name: shared-volume
        mountPath: /shared-folder
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    # ports:
    #   - containerPort: <Port>
