# this will return the server ip address
version: "3.9"
services:
    test-nginx:
        image: "nginx:1.19"
        container_name: test-nginx
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
          - "8000:80"