apiVersion: v1
kind: Service	
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - nodePort: 31111 # access this with the minikube ip, and you should see multiple ip addresses if you hit it multiple times
    port: 8000
    targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: shared-volume
        hostPath:
          path: /mnt/nfs_share/nginx-reverse-proxy.conf # please enable nfs first and copy nginx.conf to the mounted dir
      containers:
      - name: nginx
        image: "nginx:1.19"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: shared-volume
          mountPath: /etc/nginx/nginx.conf

--- 

apiVersion: v1
kind: Service	
metadata:
  name: end-server
spec:
  type: ClusterIP
  selector:
    app: fastapi
  ports:
  - port: 80
    targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      volumes:
      - name: shared-volume
        hostPath:
          path: /mnt/nfs_share/main.py # please enable nfs first and copy the file to the mounted dir
          # path: /mnt/nfs_share/nginx.conf # please enable nfs first and copy the file to the mounted dir
      containers:
      - name: fastapi-container
        image: "tiangolo/uvicorn-gunicorn-fastapi:python3.7"
        # image: "nginx:1.19"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: shared-volume
          mountPath: /app/main.py
          # mountPath: /etc/nginx/nginx.conf
        env:
          - name: MAX_WORKERS
            value: "1" # need this to avoid worker error